### ISSUE TITLE
Add visual explanation of topic modeling

### ISSUE THREAD

**Issue by yenchiah** [MultiX-Amsterdam/text-data-module#2]
Add visualizations of word clouds or plot the distribution of words for each topic in the Topic Modeling part.

Think about if you can create a task or theory questions for students to do as assignment.

Before implementing this, please discuss the implementation plan with Yen-Chia.

**Comment by amonroymz** [comment]
Implementation plan:

Add functions 
- `word_distribution(df, class)`, that returns a datafame with word counts for a given `class`.
- `visualize_word_distribution(df)`, that displays the word cloud for a given `df` with a word class distibution. We can use the [wordcloud](https://github.com/amueller/word_cloud) module for this.

My proposed structure of the Assignment for Task 3 would be:
- Tokenize and lemmatise.
- Get word distribution per class.
- Visualize word distribution per class (compare with vs without stop words).
- Get top 5 words (compare with vs without stop words).

**Comment by yenchiah** [comment]
This part looks great! Thank you so much! Based on your code, I also add the word cloud for topic modeling.
