### ISSUE TITLE
Subtle improvement in explanation of lemmatisation

### ISSUE THREAD

**Issue by amonroymz** [MultiX-Amsterdam/text-data-module#3]
When lemmatization is explained, we say:

"Unlike stemming, lemmatization can consider the context and part of speech of the word, which can make it more accurate and reliable."

But, in the code, the tokens are lemmatised one by one, so I guess context is not taken into account. 

```python
lemmatized_tokens = [lemmatizer.lemmatize(token, wordnet_pos(tag))
                     for token, tag in nltk.pos_tag(tokens)]
```

I think this could be confusing for students, should we maybe specify that this lemmatizer does not take context into account?

**Comment by yenchiah** [comment]
This is nice. Thank you!
