### ISSUE TITLE
Spacy TypeError: 'WorkDoneSentinel' object is not iterable

### ISSUE THREAD

**Issue by amonroymz** [MultiX-Amsterdam/text-data-module#4]
I sometimes get this error from Spacy. Does it happen to you? What Space version do you use?
<img width="1025" alt="image" src="https://github.com/MultiX-Amsterdam/text-data-module/assets/149786124/c1c22f23-2035-4544-bcb3-86c3d6de47ee">

**Comment by yenchiah** [comment]
I made changes to the notebook. Could you check if the problem is still there?

**Comment by amonroymz** [comment]
I changed the version to the one you include in _install_packages.sh_ and I don't get the error anymore. Thanks!
